package com.kkcom.mypib.login.svc.ws.client.stub;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 in JDK 6 Generated
 * source version: 2.1
 * 
 */
@WebServiceClient(name = "LoginWebServiceService", targetNamespace = "http://ws.svc.login.mypib.kkcom.com/", wsdlLocation = "http://localhost:8080/mypib-web/LoginWebService?wsdl")
public class LoginWebServiceService extends Service {

	private final static URL LOGINWEBSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.kkcom.mypib.login.svc.ws.client.stub.LoginWebServiceService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.kkcom.mypib.login.svc.ws.client.stub.LoginWebServiceService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:8080/mypib-web/LoginWebService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/mypib-web/LoginWebService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		LOGINWEBSERVICESERVICE_WSDL_LOCATION = url;
	}

	public LoginWebServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public LoginWebServiceService() {
		super(LOGINWEBSERVICESERVICE_WSDL_LOCATION, new QName(
				"http://ws.svc.login.mypib.kkcom.com/",
				"LoginWebServiceService"));
	}

	/**
	 * 
	 * @return returns LoginWebService
	 */
	@WebEndpoint(name = "LoginWebServicePort")
	public LoginWebService getLoginWebServicePort() {
		return super.getPort(new QName("http://ws.svc.login.mypib.kkcom.com/",
				"LoginWebServicePort"), LoginWebService.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns LoginWebService
	 */
	@WebEndpoint(name = "LoginWebServicePort")
	public LoginWebService getLoginWebServicePort(WebServiceFeature... features) {
		return super.getPort(new QName("http://ws.svc.login.mypib.kkcom.com/",
				"LoginWebServicePort"), LoginWebService.class, features);
	}

}
