package com.kkcom.mypib.login.svc.ws.client.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 in JDK 6 Generated
 * source version: 2.1
 * 
 */
@WebService(name = "LoginWebService", targetNamespace = "http://ws.svc.login.mypib.kkcom.com/")
@XmlSeeAlso({ ObjectFactory.class })
public interface LoginWebService {

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "authenticate", targetNamespace = "http://ws.svc.login.mypib.kkcom.com/", className = "com.kkcom.mypib.login.svc.ws.client.stub.Authenticate")
	@ResponseWrapper(localName = "authenticateResponse", targetNamespace = "http://ws.svc.login.mypib.kkcom.com/", className = "com.kkcom.mypib.login.svc.ws.client.stub.AuthenticateResponse")
	public boolean authenticate(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

}
